// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqcDzBudIT_bEXXT7Ye-VrJYp4kW4V5Cs',
    appId: '1:186781371875:web:c3462a53b25d1ac4c864d6',
    messagingSenderId: '186781371875',
    projectId: 'crudos-f937e',
    authDomain: 'crudos-f937e.firebaseapp.com',
    storageBucket: 'crudos-f937e.firebasestorage.app',
    measurementId: 'G-7DY1RL70KH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0uC5HcmdfStRryY4x54EmSdMsBkMBvcA',
    appId: '1:186781371875:android:e97db9b9bbde1192c864d6',
    messagingSenderId: '186781371875',
    projectId: 'crudos-f937e',
    storageBucket: 'crudos-f937e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0NWdM60531sHecm1HklgihmGR2Suq8I4',
    appId: '1:186781371875:ios:a9f09d4d059aeedac864d6',
    messagingSenderId: '186781371875',
    projectId: 'crudos-f937e',
    storageBucket: 'crudos-f937e.firebasestorage.app',
    iosBundleId: 'com.example.main',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA0NWdM60531sHecm1HklgihmGR2Suq8I4',
    appId: '1:186781371875:ios:a9f09d4d059aeedac864d6',
    messagingSenderId: '186781371875',
    projectId: 'crudos-f937e',
    storageBucket: 'crudos-f937e.firebasestorage.app',
    iosBundleId: 'com.example.main',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAqcDzBudIT_bEXXT7Ye-VrJYp4kW4V5Cs',
    appId: '1:186781371875:web:a2a1656e3d07fd94c864d6',
    messagingSenderId: '186781371875',
    projectId: 'crudos-f937e',
    authDomain: 'crudos-f937e.firebaseapp.com',
    storageBucket: 'crudos-f937e.firebasestorage.app',
    measurementId: 'G-VG34DN4FN0',
  );
}
